#!/usr/bin/env expect

source "/vagrant/test/helpers/setup.exp"

# searches at the top of the pane
#--------------------------------
display_text "/top/of_the/pane/file.txt"
tmux_ctrl_f
assert_highlighted "/top/of_the/pane/file.txt" "top of the pane absolute path"

new_tmux_pane
display_text "another/top/of_the/pane/file.txt"
tmux_ctrl_f
assert_highlighted "another/top/of_the/pane/file.txt" "top of the pane relative path"

# middle of pane searches
#------------------------
new_tmux_pane
create_output
clear_screen
display_text "/this/is/some/file.txt"
tmux_ctrl_f
assert_highlighted "/this/is/some/file.txt" "middle of the pane absolute path"

teardown_and_exit
