#!/usr/bin/env expect

source "/vagrant/test/helpers/expect_helpers.exp"
source "/vagrant/test/helpers/expect_copycat_helpers.exp"
source "/vagrant/test/helpers/expect_copycat_assertions.exp"
expect_setup

exec   "/vagrant/test/helpers/setup_tmux_conf.sh"
source "/vagrant/test/helpers/run_tmux.exp"

create_output
clear_screen
display_text "/this/is/some/path/and/file_at_the_end.txt"
tmux_ctrl_f

assert_highlighted "/this/is/some/path/and/file_at_the_end.txt"
