#!/usr/bin/env expect

source "./test/helpers/setup.exp"

enter_test_git_repo

# Match regular SHA-1 hashes
#---------------------------
git_log_reverse
tmux_alt_h
assert_highlighted "935929c4c7265666e41e727f97a87d1af00a8b40" "match regular SHA-1 hashes"

#Match shortened SHA-1 hashes
#----------------------------
git_log_reverse_short
tmux_alt_h
assert_highlighted "935929c" "match shortened SHA-1 hashes"

# quit
#-----
remove_test_git_repo
teardown_and_exit
