# a set of expect helpers

# basic setup for each script
proc expect_setup {} {
  # disables script output
  log_user 0
  # standard timeout
  set timeout 5
}

proc exit_status_false {} {
  global exit_status
  set exit_status 1
}

proc teardown_and_exit {} {
  global exit_status
  _kill_tmux_server
  exit $exit_status
}

proc create_output {} {
  # `yes` command just outputs `yes`
  send "yes\r"
  sleep 0.1
  # stop `yes` command
  send ""
  sleep 0.1
}

proc clear_screen {} {
  send ""
  sleep 0.1
}

proc display_text {text} {
  send "echo $text\r"
  sleep 0.1
}

proc new_tmux_pane {} {
  send "c"
  sleep 1
}

proc enter_irb {} {
  send "irb\r"
  sleep 1
}

proc exit_irb {} {
  send "\r"
  sleep 0.1
  send "exit\r"
  sleep 0.5
}

proc irb_display_text {text} {
  send "puts '$text'\r"
  sleep 0.3
}

# private functions

proc _kill_tmux_server {} {
  send ""
  sleep 0.1
  send "tmux kill-server\r"
  sleep 0.2
}
