# sourcing helper functions
source "./test/helpers/expect_helpers.exp"
source "./test/helpers/expect_copycat_helpers.exp"
source "./test/helpers/expect_copycat_assertions.exp"

# .tmux.conf
exec "./test/helpers/setup_tmux_conf_with_custom_searches.sh"
expect_setup

# exit status global var is successful by default
set exit_status 0

# run tmux (doesn't work when within a proc)
source "./test/helpers/run_tmux.exp"
